#!/bin/sh
# Wrap a command with a call to "mail".
# The output of the command will be mailed only if it produces output.
#
# Usage: wrap-mail <title> [<address>] -- <command> <args> ...
#
# <address> (the email address to send to) is optional.
# If not provided, it defaults to "root".
#
# Note that this will eat up all output produced by the command.
# The exit status of this script matches the exit code of "sendmail"
# (NOT the exit code of the command).

if hostname --short >/dev/null 2>&1; then
    MACHINE_NAME="$(hostname --short)"
    MACHINE_HOST="$(hostname --long)"
else
    MACHINE_NAME="$(hostname -s)"
    MACHINE_HOST="$(hostname)"
fi
USERNAME="$(id -un)"
TITLE="$1"
shift

SUBJECT="$MACHINE_NAME ($(date +%m/%d)): $TITLE"
FROM="$USERNAME@$MACHINE_NAME <$USERNAME@$MACHINE_HOST>"
TO=root
if [ "$1" != "--" ]; then
    TO="$1"
    shift
fi

if [ "$1" = "--" ]; then
    shift
else
    >&2 echo "wrap-mail: ARGUMENT ERROR: <command> must be preceded with \"--\""
    exit 2
fi

output="$("$@" 2>&1)"
if [ "$output" ]; then
    sendmail -t <<EOF
From: $FROM
To: $TO
Subject: $SUBJECT
Content-Type: text/plain
X-Mailed-By: $0

$output
EOF
fi
