#!/bin/sh
# Usage: wrap-quiet [--stderr] -- <command> <args> ...
#
# If <command> returns successfully (error code 0), then don't print any of
# its output (from either stdout or stderr). Otherwise, print all of its
# output to stdout (or stderr if the optional --stderr flag is specified).
#
# Side-effect: stdout and stderr will both be printed to stdout (or stderr
# depending on the inclusion of the --stderr flag, as noted above).

use_stderr=0
if [ "$1" = "--stderr" ]; then
    use_stderr=1
    shift
fi

if [ "$1" = "--" ]; then
    shift
else
    >&2 echo "wrap-quiet: ARGUMENT ERROR: <command> must be preceded with \"--\""
    exit 2
fi

out="$("$@" 2>&1)"
ret=$?

if [ "$ret" -eq 0 ]; then
    exit 0
fi

if [ "$use_stderr" -eq 1 ]; then
    >&2 echo "$out"
else
    echo "$out"
fi

exit $ret
