#!/bin/sh
# Change the backlight, but don't go below 1% (or above 100%).
# Requires that JaNotifier is running

NOTIFICATIONS_SOCKET=/tmp/janotifier.sock

notify() {
    vol="$1"
    icon="$2"
    echo '{
        "group": "volctrl",
        "icon": "'"$icon"'",
        "title": "Volume",
        "message": "'"$vol"'",
        "wait_time": 1.5
    }' | nc -UN "$NOTIFICATIONS_SOCKET"
}

usage() {
    echo "Usage:"
    echo "backlight-set +xx"
    echo "backlight-set -xx"
    exit 2
}

if [ "$#" -ne 1 ]; then
    usage
fi
if ! [[ $1 =~ ^[+\-][0-9]+$ ]]; then
    usage
fi

new="$(python2 -c "print (int($(xbacklight -get)) $1)")"
if [ "$new" -lt 1 ]; then
    new=1
elif [ "$new" -gt 100 ]; then
    new=100
fi

echo '{
    "group": "backlight",
    "title": "Brightness",
    "icon": "display-brightness-symbolic",
    "message": "'"$new"'%",
    "wait_time": 1.5
}' | nc -UN "$NOTIFICATIONS_SOCKET"

exec xbacklight -set "$new"
